Fix NameError
undefined local variable or method `process_id' is raise with new
sidekiq version. This issue is because process_id method is replace by
process_nonce. Replace this call by the handle method identity. Now
this middleware is retro compatible.